version: '3'

services:
  app:
    image: rails-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    volumes:
      - ./:/app
    tmpfs:
      - /app/tmp/pids
    ports:
      - 3000:3000
    working_dir: /app
    tty: true
    command: docker/app/startup.sh

  database:
    image: mariadb
    volumes:
      - "database:/var/lib/mysql"
      - ".:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

volumes:
  database:
